### ISSUE TITLE
Exception putting items into hoppered barrels.

### ISSUE THREAD

**Issue by acsmars** [lukecarr/TABBA#1]
The following error and the destruction of the stored item happen when right clicking to place an item into an empty barrel that has an active hopper below it.

`[18:11:51 ERROR]: Could not pass event InventoryMoveItemEvent to TABBA v0.1.0
java.lang.IllegalArgumentException: Material cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.14.4.jar:git-Paper-146]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73) ~[patched_1.14.4.jar:git-Paper-146]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:61) ~[patched_1.14.4.jar:git-Paper-146]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:49) ~[patched_1.14.4.jar:git-Paper-146]
        at dev.tinkererr.tabba.listener.HopperListener.lambda$onHopperTransfer$0(HopperListener.java:40) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at dev.tinkererr.tabba.listener.HopperListener.onHopperTransfer(HopperListener.java:35) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor174.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-146]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-146]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-146]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-146]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[patched_1.14.4.jar:git-Paper-146]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.callPullMoveEvent(TileEntityHopper.java:303) ~[patched_1.14.4.jar:git-Paper-146]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.hopperPull(TileEntityHopper.java:246) ~[patched_1.14.4.jar:git-Paper-146]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:443) ~[patched_1.14.4.jar:git-Paper-146]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.lambda$a$3(TileEntityHopper.java:420) ~[patched_1.14.4.jar:git-Paper-146]
        at java.util.stream.MatchOps$2MatchSink.accept(MatchOps.java:119) ~[?:?]
        at java.util.stream.Streams$RangeIntSpliterator.tryAdvance(Streams.java:82) ~[?:?]
        at java.util.stream.IntPipeline.forEachWithCancel(IntPipeline.java:163) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.IntPipeline.anyMatch(IntPipeline.java:513) ~[?:?]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:418) ~[patched_1.14.4.jar:git-Paper-146]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.lambda$tick$0(TileEntityHopper.java:118) ~[patched_1.14.4.jar:git-Paper-146]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:139) ~[patched_1.14.4.jar:git-Paper-146]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.tick(TileEntityHopper.java:117) ~[patched_1.14.4.jar:git-Paper-146]
        at net.minecraft.server.v1_14_R1.World.tickBlockEntities(World.java:856) ~[patched_1.14.4.jar:git-Paper-146]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:382) ~[patched_1.14.4.jar:git-Paper-146]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[patched_1.14.4.jar:git-Paper-146]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-146]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-146]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-146]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

Great plugin btw :)

**Comment by acsmars** [comment]
Also occurs when a hopper places an item into an empty barrel with a hopper pulling out from the barrel.

**Comment by lukecarr** [comment]
This has been fixed in v0.1.1. A release should be going live in a few minutes over on the [releases page](https://github.com/lukecarr/TABBA/releases)!

**Comment by acsmars** [comment]
Awesome, thanks, again, love the mod :)
